### PR TITLE
fork to create child process

### PR DESCRIPTION
**Pull request by Tednic**
Abg, please assist to review the fork.c file to create a child process.

### CODE REVIEW

**Comment by Abysemilla97** [comment]
You have misspelled some words in the file

**Comment by Abysemilla97** [comment]
In line 48, instead of Pathnane, it should be Pathname, and in line 7 place of numbee, it should be number.

**Comment by Tednic** [comment]
Correction made.

**Comment by Abysemilla97** [comment]
Alright good to go.

**Pull request merged**
